name: tor-browser-unofficial
adopt-info: tor-browser
summary: Tor Browser
description: |
  Fingerprinting resisting browser bundled with Tor

  ___
  It's highly recommended to enable the browser sandbox:

  sudo snap connect tor-browser-unofficial:browser-support
source-code: https://github.com/iomezk/snap-torbrowser
license: MPL-2.0
base: core22
confinement: strict
grade: stable
icon: icon.svg
compression: lzo

apps:
  tor-browser-unofficial:
    extensions: [gnome]
    command: Browser/tor-browser
    plugs:
    - audio-playback
    - browser-support
    - home
    - network
    - network-bind
    - removable-media
    - unity7  # dbus path=/org/a11y/bus member=Get

environment:
  HOME: $SNAP_USER_COMMON
  PATH: $SNAP/Browser:$PATH

plugs:
  browser-support:
    allow-sandbox: true
  ffmpeg-2204:
    interface: content
    default-provider: ffmpeg-2204
    target: ffmpeg-platform

parts:
  local:
    source: snap/local/
    source-type: local
    plugin: dump
    prime:
    - -patches/
  libpci:
    source: https://mj.ucw.cz/download/linux/pci/pciutils-3.10.0.tar.gz
    source-checksum: sha256/7deabe38ae5fa88a96a8c4947975cf31c591506db546e9665a10dddbf350ead0
    source-type: tar
    plugin: make
    make-parameters:
    - ZLIB=no
    - DNS=no
    - SHARED=yes
    - LIBKMOD=no
    - HWDB=no
    - PREFIX=/
    organize:
      lib/libpci.so*: Browser/
    prime:
    - Browser/
  tor-browser:
    # https://dist.torproject.org/torbrowser/
    source: https://dist.torproject.org/torbrowser/13.0.5/tor-browser-linux-x86_64-13.0.5.tar.xz
    source-checksum: sha256/599abc8a0eb632edeae8ead549a3db7ba30b43aa6f14da37c903170bb3c21896
    source-type: tar
    plugin: dump
    build-packages:
    - jq
    - patch
    - unzip
    - zip
    override-build: |
      craftctl default
      cd "$CRAFT_PART_INSTALL"
      craftctl set "version=$(jq -r .version Browser/tbb_version.json)"
      chmod -R go=rX .
      mv Browser/TorBrowser/Data/Browser Browser/TorBrowser/Data/firefox
      mv Browser/TorBrowser/Data Browser/TorBrowser/.tor\ project
      # decompressing omni.ja to save space and speed up
      for f in Browser/omni.ja Browser/browser/omni.ja; do
        unzip -q "$f" -d omni
        rm -f "$f"
        cd omni
        zip -0DXqr "../$f" *
        cd ..
        rm -rf omni
      done
    prime:
    - -Browser/.config
    - '-Browser/TorBrowser/.tor project/firefox/Caches'
    - -Browser/TorBrowser/Docs
    - -Browser/TorBrowser/Tor/lib*
    - -Browser/abicheck
    - -Browser/application.ini
    - -Browser/browser/features
    - -Browser/execdesktop
    - -Browser/fonts/000_README.txt
    - -Browser/firefox
    - -Browser/icons
    - -Browser/libstdc++
    - -Browser/platform.ini
    - -Browser/plugin-container
    - -Browser/precomplete
    - -Browser/removed-files
    - -Browser/start-tor-browser*
    - -Browser/tbb_version.json
    - -Browser/update*
    - -start-tor-browser.desktop
